version: '3.1'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  redis:
    image: 'redis'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8001:8001
  mongo-gui:
    image: mongo-express:0.54
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${DB_SERVICE_NAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
        - "8081:8081"
    depends_on:
      - mongo
  api:
    container_name: api
    volumes:
      - ./:/home/gojsuser/dxl
    working_dir: /home/gojsuser/dxl
    build:
      dockerfile: Dockerfile.local
      context: .
    environment:
      MONGO_APP_USER: ${MONGO_ROOT_USER}
      MONGO_APP_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_APP_DB: ${MONGO_INITDB_NAME}
      DB_SERVICE_NAME: ${DB_SERVICE_NAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: redis
    ports:
      - 8080:8080
    command: go run .
    depends_on:
      - mongo
      - redis
  ui:
    container_name: ui
    volumes:
      - ./dxl_ui:/home/gojsuser/ui
    working_dir: /home/gojsuser/ui
    build: 
      dockerfile: ./frontend/Dockerfile
      context: .
    ports:
      - 3000:3000
    command: yarn start
    depends_on:
      - api
